/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projek.akhir.klp7;

public class App {
    public String getGreeting() {
        return "Hallo kalian";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
